# Week 4 Assignment
## Q1

In [1]:
# First of all import the Numpy funcation

import numpy as np

# Create 'a' array

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

# Create 'b' array

b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Create 'c' array which is the intersection of a and b

c = np.intersect1d(a,b)

c

array([2, 4])

## Q2

In [2]:
# For this question, we can use the arange() and reshape() function
# Put the range into arange and 3 by 5 into reshape.

d = np.arange(1,16).reshape(3,5)

# Than use Transpose function

d.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## Q3 

In [3]:
# Create array a
a = np.array([12, 5, 7, 15, 3, 1, 8])

# Creare array b
b = np.array([14, 6, 3, 11, 19, 12, 5])

# Use the "setdiff1d" to remove the value in array a that also in array b 
a = np.setdiff1d(a,b)

# print a to check out if correct.
a


array([ 1,  7,  8, 15])

## Q4

In [4]:
# Create an array with range from 0 to 1548(miles)
arr = np.random.randint(40,60,30,int)

# Than create a trip list 
trip =[]

# Write a break loop to pick number from 'arr' array and append into the 'trip' list

for x in arr:
    x = 0+x
    trip.append(x)
    if len(trip)==31:
        break

# Create 4 list. Manally insert 0(represent 0 miles) every 6 days 
cum_trip  = np.insert(trip,6,0)
cum_trip1 = np.insert(cum_trip,13,0) 
cum_trip2 = np.insert(cum_trip1,20,0)  
cum_trip3 = np.insert(cum_trip2,27,0)

# Create a new array use cumsum funcation to accumulate the mileages
cum_trip4 =np.cumsum(cum_trip3)

# Create a new array to insert the last vaule to be the 1548 miles
cum_trip_list = np.insert(cum_trip4,34,1548)

# print the array to see if it meet the qualication.

print(cum_trip_list)

print(np.ediff1d(cum_trip_list))

print(f'Spend {len(cum_trip_list)} days totally.')

[  52  108  148  206  247  290  290  347  390  448  491  548  596  596
  643  694  749  796  849  907  907  948 1001 1043 1096 1140 1191 1191
 1231 1287 1343 1395 1451 1497 1548]
[56 40 58 41 43  0 57 43 58 43 57 48  0 47 51 55 47 53 58  0 41 53 42 53
 44 51  0 40 56 56 52 56 46 51]
Spend 35 days totally.


## Q5

In [1]:
# First import the CSV. file.

import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  # Remove the CWD from sys.path while we load stuff.


numpy.ndarray

In [54]:
# What is the maximum yearly NYC consumption of water in millions of gallons per day?
# First use max function to see the maximum of each column

water_consumption = np.max(nyc_water,axis = 0)

# Form the website we know the 3rd column indicate the water comsuption.
# Use slicing function to show the maximum water consumption.

water_consumption[2]

# Print the result.
print(f'The maximum water consumption is: {int(water_consumption[2])} million gallons per day')

The maximum water consumption is: 1512 million gallons per day


In [57]:
# How many calendar years are represented within this data set?
# Use the shape function the number of the rows could represent the number of years

num_years = nyc_water.shape

# Slicing the result
num_years[0]

# Print the result
print(f'There are {num_years[0]} calendar years are represented within this data set')

There are 39 calendar years are represented within this data set


In [62]:
# What is the mean and the standard deviation of the per capita daily water consumption?
# Use the mean function to check out the mean of each column

mean_nyc_water = nyc_water.mean(axis=0)

mean_nyc_water

# Use the Std functionl to check out the standrad deviation of each column

std_nyc_water = nyc_water.std(axis=0)

std_nyc_water

# Use slicing function to show the 4th the mean and std for 4th column(Per Capita)

mean_nyc_water[3], std_nyc_water[3]

# Print the result
print(f'The mean of Per Capita is {mean_nyc_water[3]}, and the Standard deviation of Per Capita is {std_nyc_water[3]}')

The mean of Per Capita is 160.30769230769232, and the Standard deviation of Per Capita is 31.51894330370624


In [10]:
# Use the diff function to show the differences between each elements in each column.

pop_diff = np.diff(nyc_water, axis=0)

pop_diff

# Use slicing function to show the differences of 2nd column.
print(pop_diff[:,1])

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
